Upgrade django version to 2.2
TwigWorld/django-rottweiler pull request #8
Opened 2023-01-11 08:40 UTC by Arun-integrella

2023-01-26 14:20 UTC, davismr requested changes
Is this for a django 2.2, python 3.7 compatible project?

Update setup.py to reflect correct python version, or jsut drop it.

Tests are not passing:

  File "/Users/mdavis/sites/rottweiler/src/django-rottweiler/rottweiler/view_helpers.py", line 22, in get_all_rules
    for k, v in registry.iteritems():
AttributeError: 'collections.defaultdict' object has no attribute 'iteritems'

2023-01-30 13:31 UTC, davismr commented
This is the line that needs fixing:

https://github.com/TwigWorld/django-rottweiler/blob/2caac489d6df3e8bf168b6ab884ec64920879e31/rottweiler/view_helpers.py#L22

2023-02-02 10:30 UTC, davismr approved these changes

2023-02-16 16:19 UTC, davismr requested changes

2023-02-16 16:19 UTC, davismr commented on rottweiler/view_helpers.py
> +    from django.core.urlresolvers import RegexURLPattern as URLPattern, RegexURLResolver as URLResolver
Keep imports on separate lines

add comment to say these are python2, we will need to know which ones to delete later

2023-02-16 16:19 UTC, davismr commented on rottweiler/view_helpers.py
> +            views.extend(extract_views_from_urlpatterns(patterns, base + p.pattern.regex.pattern))
This fails a test in python2, syntax should be:

p.regex.pattern

probably easiest to add a switch PYTHON3 = True in import try at top, and use that throughout to decide which syntax to use

2023-02-21 09:20 UTC, Arun-integrella commented
Superseeded by PR9.

2023-02-21 09:20 UTC, closed without merging